In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from word2number import w2n


In [2]:
df = pd.read_csv('E:\\MachineLearning\\1LinearRegressionClass\\Excersise_multipleLinearRegression\\interview.csv')
df

experience  testScore  interviewScore  salary
0        NaN        8.0               9   50000
1        NaN        8.0               6   45000
2       five        6.0               7   60000
3        two       10.0              10   65000
4      seven        9.0               6   70000
5      three        7.0              10   62000
6        ten        NaN               7   72000
7     eleven        7.0               8   80000

In [3]:
df = df.fillna({'experience': 0})

for i in range(len(df['experience'])):
    if df['experience'][i]!=0:
        print(df['experience'][i])
        df['experience'][i] = w2n.word_to_num(df['experience'][i]);
        
df


five
two
seven
three
ten
eleven


C:\Users\kumar\AppData\Local\Temp\ipykernel_8252\1480192953.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = w2n.word_to_num(df['experience'][i]);
C:\Users\kumar\AppData\Local\Temp\ipykernel_8252\1480192953.py:6: Set

experience  testScore  interviewScore  salary
0          0        8.0               9   50000
1          0        8.0               6   45000
2          5        6.0               7   60000
3          2       10.0              10   65000
4          7        9.0               6   70000
5          3        7.0              10   62000
6         10        NaN               7   72000
7         11        7.0               8   80000

In [4]:
import math 
median_test_score = math.floor(df.testScore.median())
median_test_score

8

In [5]:
df = df.fillna({'testScore': median_test_score})

In [6]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(df[['experience','testScore','interviewScore']],df.salary)

LinearRegression()

In [7]:
regressor.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [8]:
regressor.intercept_

17737.26346433768

In [9]:
regressor.predict([[2,9,6]])

c:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [10]:
y_pred = regressor.predict([[12,10,10]])
y_pred

c:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [11]:
import pickle

In [12]:
with open('model_pickle','wb') as f:
    pickle.dump(regressor,f)

In [13]:
with open('model_pickle','rb') as f:
    model = pickle.load(f)

In [14]:
model.predict([[2,9,6]])

c:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [16]:
from joblib import dump , load

In [17]:
dump(regressor,'joblibSavingfile')

['joblibSavingfile']

In [18]:
tempLoadJoblib = load('joblibSavingfile')

In [19]:
tempLoadJoblib.predict([[2,9,6]])

c:\Users\kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])